services:
  mongodb:
    image: mongo:8
    container_name: taskhub-mongodb
    restart: unless-stopped

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

    volumes:
      - mongodb_data:/data/db

    networks:
      - taskhub-network

  backend:
    image: emex2275/taskhub-backend:v1
    container_name: taskhub-backend
    restart: unless-stopped

    depends_on:
      - mongodb

    ports:
      - "3001:3001"

    environment:
      PORT: ${PORT}
      MONGODB_URI: ${MONGODB_URI}

    networks:
      - taskhub-network

  frontend:
    image: emex2275/taskhub-frontend:v1
    container_name: taskhub-frontend
    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "3000:3000"

    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}

    networks:
      - taskhub-network

volumes:
  mongodb_data:

networks:
  taskhub-network:
    driver: bridge