services:
   db:
      image: mongo:latest
      restart: always
      environment:
         MONGO_INITDB_ROOT_USERNAME: admin
         MONGO_INITDB_ROOT_PASSWORD: password
         MONGO_INITDB_DATABASE: taskhub
      ports:
         - "27017:27017"
      volumes:
         -  mongodb_data:/data/db  
      healthcheck:
         test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
         interval: 5s
         timeout: 5s
         retries: 5
   
   backend:
      build:
         context: ./backend
         dockerfile: Dockerfile
         tags:
         - task-backend:latest
      restart: always
      env_file:
         - ./backend/.env
      ports:
         - "5000:5000" 
      depends_on:
         db:
            condition: service_healthy

   frontend:
      build:
         context: ./frontend
         dockerfile: Dockerfile
      restart: always
      ports:
         - "3001:3000"  
      depends_on:
         - backend         
volumes:
   mongodb_data: