version: "3.9"

services:
  mongodb:
    image: mongo:8
    container_name: taskhub-mongod
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - taskhub-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: taskhub-backend

    restart: unless-stopped

    ports:
      - "3001:3001"

    depends_on:
      - mongodb

    environment:
     PORT: ${PORT}
     MONGODB_URI: ${MONGODB_URI}
    networks:
      - taskhub-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: taskhub-frontend

    restart: unless-stopped

    ports:
      - "3000:3000"

    depends_on:
      - backend

    environment:
      NEXT_PUBLIC_API_URL:${NEXT_PUBLIC_API_URL}

    networks:
      - taskhub-network

volumes:
  mongodb_data:

networks:
  taskhub-network: