#Install dependencies
FROM node:20-alpine AS deps

WORKDIR /app

COPY package*.json ./

RUN npm ci

#Build 
FROM node:20-alpine AS builder

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules

COPY . .

RUN npm run build

#Install production dependencies
FROM node:20-alpine AS prod-deps

WORKDIR /app

COPY package*.json ./

RUN npm ci --omit=dev

#Runner 
FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production


RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nestjs

RUN chown -R nestjs:nodejs /app


COPY --from=prod-deps --chown=nestjs:nodejs /app/node_modules ./node_modules

COPY --from=builder --chown=nestjs:nodejs /app/dist ./dist

RUN chmod -R 755 /app

USER nestjs

EXPOSE 3001

CMD ["node", "dist/main.js"]